export const GET_THONG_KE_SO_LUONG_VE = 'GET_THONG_KE_SO_LUONG_VE';
export const GET_THONG_KE_SL_VE_THEO_NAM = 'GET_THONG_KE_SL_VE_THEO_NAM';
export const GET_THONG_KE_DOANH_THU_THEO_NAM = 'GET_THONG_KE_DOANH_THU_THEO_NAM';
export const GET_THONG_KE_DOANH_THU = 'GET_THONG_KE_DOANH_THU'